# Meta data
name:         Samanvay
authors:      Mihir
description:  Samanvay website

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
source:       website
port:         4000
url:          http://samanvayorg.github.io
